ordered_fields = [
    # Prioridad alta (ya tenías)
    "ImagenURL",
    "Precio",
    "Score",
    "Título",
    "Enlace",
    "Marca",
    "Modelo",
    "Versión",
    "Motor",
    "Año",
    "Kilómetros",
    "Color",
    "Control de tracción",
    "Dirección",
    "Potencia",
    "Puertas",
    "Capacidad de personas",
    "Capacidad del tanque",
    "Tipo de carrocería",
    "Tipo de combustible",
    "Transmisión",
    "Ubicación",

    # Seguridad y características funcionales
    "Airbag conductor",
    "Airbag para conductor y pasajero",
    "Frenos ABS",
    "Control de estabilidad",
    "Cierre centralizado de puertas",
    "Vidrios eléctricos",
    "Cierre automático de vidrios" ,
    "Desempañador trasero",
    "Aire acondicionado",
    "Climatizador",
    "Sensor de parqueo",
    "Sensor de lluvia",
    "Con cámara de reversa",
    "Computadora de abordo",
    "Blindado", 

    # Multimedia y conectividad
    "Bluetooth",
    "CD",
    "AM/FM",
    "Reproductor de MP3",
    "Entrada USB",
    "Entrada auxiliar",
    "DVD",
    "Comando remoto para radio en el volante",

    # Extras y confort
    "Techo corredizo",
    "Tapizado de cuero",
    "Tercera luz de freno led",
    "Alarma",
    "Alarma de luces encendidas",
    "Apertura remota de baúl",
    "Limpia/lava luneta",
    "Faros antinieblas traseros",
    "Luces con regulación automática",
    "Piloto automático",
    "Porta vasos",
    "Porta equipaje en techo",
    "Soporte para llanta de repuesto",
    "Llantas de aleación",
    "Defensa delantera",
    "Sistema ISOFIX",

    # Garantías y condiciones comerciales
    "Con garantía de fábrica",
    "Con garantía mecánica",
    "Con precio negociable",
    "Venpermuta",
    "Único dueño",

    # Técnicos complementarios
    "Distancia entre ejes",
    "Largo x Ancho",
    "Largo x Altura x Ancho",
    "Válvulas por cilindro",
    "Último dígito de la placa",
    "Paridad de la placa",
    
    # Eléctrico
    "Autonomia de la batería",
    "Capacidad de la batería",
    "Tipo de batería",
    "Tiempo de carga",
    "Tipo de cargador",
]
